application: popmilo1984
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/images
  static_dir: static/images

- url: /static/css
  static_dir: static/css

- url: /static/javascript
  static_dir: static/javascript

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

includes:
- mapreduce/include.yaml
